version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  go-service:
    build: .
    container_name: go-service
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
